### ISSUE TITLE
Beispielflow: Homematic Klingelsensor (HM-Sen-DB-PCB) an Homekit anbinden.

### ISSUE THREAD

**Issue by Jemeins** [HM-RedMatic/RedMatic#106]

**Comment by hobbyquaker** [comment]
Habe nun doch den HM-Sen-DB-PCB und den HmIP-DBB eingebaut, es wird ein Accessory mit einem Doorbell Service angelegt. Wird aber wie gesagt nicht von der Home App unterstützt, vielleicht kann man ihn aber gebrauchen um eine Automation zu triggern oder eine Push Nachricht zu generieren, hab ich noch nicht getestet.

**Comment by Jemeins** [comment]
Vielen Dank! Wie generiert man denn eine Push Nachricht?

**Comment by hobbyquaker** [comment]
Sollte ganz ohne weitere Konfiguration funktionieren wenn der HM-Sen-DB auslöst.

**Comment by hobbyquaker** [comment]
Ich vermute allerdings man braucht dafür aber eine "Homekit Zentrale" (Apple TV)

**Comment by Jemeins** [comment]
Super vielen Dank! Funktioniert wirklich gut.
Ich hatte mein iPhone eben auf "nicht Stören" kein wunder das es nicht funktioniert hat ;D

**Comment by hobbyquaker** [comment]
Top, dann schließ ich den Issue hier.
