### ISSUE TITLE
rmupdate compatibility

### ISSUE THREAD

**Issue by derkopp** [HM-RedMatic/RedMatic#109]
Hallo, 
die installation via rmupdate funktioniert generell sehr gut.
Wünschenswert wäre es noch, wenn rmupdate automatisch erkennt, dass eine neue Version vorliegt und man direkt installieren kann - ohne bei jedem Update den Link zur tgz kopieren zu müssen.

**Comment by hobbyquaker** [comment]
Hmm, bei mir funktioniert das: 
![image](https://user-images.githubusercontent.com/2503307/48981352-7a46e680-f0d4-11e8-9a0f-d08be0203a9e.png)
Was passiert denn wenn Du im Browser `http://<ccu-adresse>/addons/redmatic/update_check.cgi` aufrufst?

**Comment by hobbyquaker** [comment]
related: #65

**Comment by derkopp** [comment]
Aktuell wird dann die update.cgi als Download angeboten, siehe #108
Ich teste nochmal, sobald das durch ist.

**Comment by derkopp** [comment]
Hier ist die JSON:
<img width="656" alt="bildschirmfoto 2018-11-25 um 18 07 54" src="https://user-images.githubusercontent.com/29502380/48982006-0e1cb080-f0dd-11e8-8d7f-d468f13756af.png">
Die Download URL ist leer.

**Comment by helmsklamm** [comment]
Hi Sebastian. Vielleicht hilft das: bei mir gab es auch Probleme dass die cgi Datei zum Download Angeboten (statt ausgeführt) wurde.
Das hing mit den Sicherheitseinstellungen des neuen Security Wizards zusammen. Kann mich leider nicht erinnern welches Setting genau das war aber folgender Tipp.
Custom settings (Benutzerdefiniert) verwenden und mal alles auf voll Zugriff stellen.
Geht’s dann evtl wieder? Danach sukzessive die Settings so restriktiv wie mögl. Setzen.....

**Comment by hobbyquaker** [comment]
ich schließe hier mal, ich geh davon aus dass das die gleiche ursache hat wie #108 - allerdings kann ich da nix dran machen. Wird wieder funktionieren wenn Jens ein RaspberryMatic Bugfix Release veröffentlicht hat oder wenn Jan sein Addon anpasst.

**Comment by derkopp** [comment]
Ich mache mal wieder auf - auch mit neustem raspberrymatic, rmupdate und redmatic funktioniert die Anzeige eines Updates über rmupdate nicht.

<img width="1138" alt="bildschirmfoto 2018-12-09 um 13 55 06" src="https://user-images.githubusercontent.com/29502380/49697612-0b7c8980-fbba-11e8-9200-1ff4dea7932b.png">

addons/redmatic/update_check.cgi:
1.9.15


addons/rmupdate/rest.cgi?sid=@zIdf2Fgono@&path=/get_addon_info
[{
    "available_version": "2.4.1",
    "cgi": "/usr/local/etc/config/addons/www/mediola/update-check.cgi",
    "cgi_interpreter": "/bin/tclsh",
    "config_url": "/addons/mediola/index.html",
    "download_url": "",
    "id": "97NeoServer",
    "name": "NEO SERVER",
    "operations": "uninstall restart",
    "update": "/addons/mediola/update-check.cgi",
    "version": "2.4.0"
}, {
    "available_version": "",
    "cgi": "/usr/local/etc/config/addons/www/redmatic/update_check.cgi",
    "cgi_interpreter": "/usr/bin/env tclsh",
    "config_url": "/addons/redmatic/settings.cgi",
    "download_url": "",
    "id": "redmatic",
    "name": "RedMatic",
    "operations": "restart uninstall",
    "update": "/addons/redmatic/update_check.cgi",
    "version": "1.9.14"
}, {
    "available_version": "1.13.5",
    "cgi": "/usr/local/etc/config/addons/www/rmupdate/update.cgi",
    "cgi_interpreter": "/bin/tclsh",
    "config_url": "/addons/rmupdate",
    "download_url": "https://github.com/j-a-n/raspberrymatic-addon-rmupdate/raw/master/rmupdate.tar.gz",
    "id": "rmupdate",
    "name": "System-Update",
    "operations": "uninstall",
    "update": "/addons/rmupdate/update.cgi",
    "version": "1.13.5"
}]

Die Download-URL ist leer.
