### ISSUE TITLE
Datenpunkt Events fehlen: HM-CC-TC Setpoint

### ISSUE THREAD

**Issue by BernadoEco** [HM-RedMatic/RedMatic#113]
@all
mir ist aufgefallen, das bei der oben genannten Wandtermostat der Wert  "SETPOINT"(Solltemperatur) nicht ausgegeben wird (z.B. bei MQTT).
 
Folgende Werte werden ausgegeben: 
HUMIDITY
TEMPERATURE 
ADJUSTING_COMMAND
ADJUSTING_DATA

Ist das so korrekt oder habe ich was übersehen? Wenn es fehlt wäre das noch zu ergänzen?

Gruß

**Comment by hobbyquaker** [comment]
Ich glaube Du bist auf dem falschen Kanal. `HUMIDITY` und `TEMPERATURE` ist auf Kanal 1, `SETPOINT` auf Kanal 2.

**Comment by BernadoEco** [comment]
Der Wert SETPOINT wird nicht vom ccu-mqtt vom Wandtermostat HM-CC-TC an den MQTT-Server gesendet, wie z.B. beim HM-CC-RT-DN (SET_TEMPERATURE)und wird auch nicht auf den Kanal2 ausgegeben. Setzen über das Topic hm/set ist kein Problem. Wäre es möglich das auch bei dem HM-CC-TC der Wert gesendet wird, so das man auch ohne Änderungen der Solltemperatur einfach nur den Status bekommt.

**Comment by hobbyquaker** [comment]
Bin hier immer noch etwas ratlos. Ich bekomme SETPOINT events über MQTT auf Kanal 2.
```
$ mosquitto_sub -C 1 -h mqtt -t 'hm/status/+/SETPOINT' -v
hm/status/Temperatur Arbeitszimmer Soll/SETPOINT {"val":20,"ts":1545567583246,"lc":1545554099000,"hm":{"ccu":"localhost","iface":"BidCos-RF","device":"JEQ0230153","deviceName":"Thermostat Arbeitszimmer","deviceType":"HM-CC-TC","channel":"JEQ0230153:2","channelName":"Temperatur Arbeitszimmer Soll","channelType":"CLIMATECONTROL_REGULATOR","channelIndex":2,"datapoint":"SETPOINT","datapointName":"BidCos-RF.JEQ0230153:2.SETPOINT","datapointType":"FLOAT","datapointMin":6,"datapointMax":30,"datapointDefault":21,"datapointControl":"TEMP.SETPOINT","valuePrevious":20,"valueStable":20,"rooms":["Arbeitszimmer"],"room":"Arbeitszimmer","functions":["Heizung"],"function":"Heizung","ts":1545567583246,"tsPrevious":1545554099000,"lc":1545554099000,"change":false,"cache":false,"stable":true}}
```

**Comment by hobbyquaker** [comment]
> so das man auch ohne Änderungen der Solltemperatur einfach nur den Status bekommt.

Kann es sein dass die Nachricht nicht retained wird? Du solltest in dem Node den Du an den "ccu - mqtt" Node hängst um die Nachrichten auf MQTT zu publishen bei Retain `false` ausgewählt hast? Da sollte nichts ausgewählt sein:
<img width="1489" alt="bildschirmfoto 2018-12-23 um 21 07 36" src="https://user-images.githubusercontent.com/2503307/50387198-e2e6aa80-06f6-11e9-8ce6-36990455847a.png">

Wenn Du das leer lässt werden alle Datenpunkte außer "one-shot-events" wie z.B. Tastendruck `PRESS_SHORT` mit retain Flag published, dann bekommst Du den letzten Wert bei einem Subscribe sofort.
