### ISSUE TITLE
HM-LC-Sw1-FM Anschluß an Schalter funktioniert nicht

### ISSUE THREAD

**Issue by FuggyD** [HM-RedMatic/RedMatic#114]
Ich steige derzeit von mediola auf Node-Red um. Dabei habe ich jedoch eine Problematik:
ich habe einen HM-LC-Sw1-FM Schaltaktor Unterputz installiert und an einen Schalter angeschlossen.
ICh habe erfolgreich einen Flow erstellt der mir das Licht ein-aus schaltet. Nur die Betätigung des Schalters funktioniert nun nicht mehr.
Gibt es eine Möglichkeit einen Befehl an den Aktor über Node-Red zu schicken um die Schalterbetätigung zu simulieren um dadurch ggf. den Fehler per Debug ausgeben zu lassen?

**Comment by Sineos** [comment]
Siehe https://github.com/HM-RedMatic/RedMatic/wiki/Flow-simple-toggle-light für das generelle Prinzip

**Comment by FuggyD** [comment]
hi, danke für den Hinweis. Aber in dem Beispiel wird ein anderer "Sender" als Schalter verwendet. Ich habe direkt am Aktor ein Kabel von einem GIRA Schalter angeschlossen (S1) und dieser scheint jetzt nicht mehr zu funktionieren. Also der Aktor reagiert nicht mehr wenn am S1 Spannung anliegt. 
Ein Ansatz wäre den Aktor zu überprüfen ob am S1 Spannung anliegt und dann den Aktor msg.payload = 1 oder 0 zu übergeben; kann diesen Wert aber nicht abgreifen (bzw. weiß nicht ob das überhaupt geht).

Ich habe einen externen Sender (Fernbedienung) so eingerichtet dass dieser den Aktor einschaltet; aber die "offline" Variante funktioniert jetzt nicht mehr.

**Comment by Hypnos3** [comment]
Der Eingang S1 ist intern im HM-LC-Sw1-FM verknüpft. Du kannst in Node Red ncith den Eingang abgreifen, sondern nur den STATE des Ausganges. Das kann genauso wie https://github.com/HM-RedMatic/RedMatic/wiki/Flow-simple-toggle-light erfolgen.

Eventuell musst du den HM-LC-Sw1-FM aber noch in ein Dummy Programm in der CCU hauen wegen dem reportValueUsage (https://github.com/hobbyquaker/RedMatic/issues/61).

**Comment by hobbyquaker** [comment]
Ich halte es für sehr unwahrscheinlich bis ausgeschlossen dass Du das Verhalten des Taster-Eingangs durch RedMatic beeinflusst hast. Ich würde das mal durchmessen, glaube eher hier gibt es ein elektrisches Problem. Du sprichst auch von einem "Schalter", dieser Eingang ist meines Wissens aber nur für Taster geeignet. Siehe auch Seite 18 hier: https://www.eq-3.de/Downloads/eq3/downloads_produktkatalog/homematic/bda/HM-LC-Sw1-FM_UM_GE_eQ-3_150911-web.pdf

**Comment by Sineos** [comment]
>  Ich habe direkt am Aktor ein Kabel von einem GIRA Schalter angeschlossen (S1) und dieser scheint jetzt nicht mehr zu funktionieren

Hier würde ich auch im ersten Schritt von einem elektrischen Problem ausgehen. Ist der Gira wirklich ein Schalter oder ein Taster? Zitat der Anleitung:

> Die Steuereingänge werden mit Netzspannung beschaltet. Verwenden Sie ausschließlich netzspannungsfeste Taster und Leitungen! Schließen Sie an die Eingänge nur Taster und keine Schalter an! Dieses würde zur Fehlfunktion des Gerätes führen (Anlernmodus)!

**Comment by Sineos** [comment]
Ups, lesen hilft. Sorry @hobbyquaker :-)

**Comment by FuggyD** [comment]
hmm. das könnte ein Ansatz sein. Ich habe den Aktor in einer Wechselschaltung drin (also Schalter, kein Taster). Musste den vor einigen Jahren (4) ersetzen weil der HM-LC-Sw1PBU-FM nicht mehr wollte (nebenbei -> das ist jetzt schon der 6. Defekte HM-LC-Sw1PBU-FM). Lief aber mit dem Sw1 aber einwandfrei. 
Habe im Keller denselben Aktor an einem Taster. Werde den mal Testen und wenn es da dann klappt mittels Taster und Node-Red zu bedienen das könnte es daran liegen dass der Aktor defekt ist. Dann muss ich doch wieder auf den HM-LC-Sw1PBU-FM umsteigen.
Ich werde weiter berichten.

**Comment by FuggyD** [comment]
Ok. Habe es an einem anderen Aktor wo ein Taster angeschlossen ist getestet, funktioniert einwandfrei. Denke eure Vermutung ist richtig das der Aktor einen Hau hat weil ich einen Schalter angeschlossen habe.

Habe 4 Wechselschaltungen die ich wohl anders aufbauen muss.
Andere Sache die mir auch gerade aufgefallen ist:
HM-PBI-4-FM ist in den homematicInvalidDevices gelistet. Diese habe ich recht häufig als Sender in Verwendung.
Ist geplant diese zu RedMatic hinzuzufügen oder bleiben die weg?

**Comment by FuggyD** [comment]
ups, war im falschen Repo (HM-RedMatic/RedMatic-HomeKit).
Unterstützt RedMatic den HM-PBI-4-FM?

**Comment by hobbyquaker** [comment]
RedMatic bzw. node-red-contrib-ccu unterstützt ohne Ausnahme alle Homematic Aktoren. RedMatic-HomeKit legt Taster nicht automatisch an - aber man kann sie bei Bedarf mit dem Homekit-Event Node komfortabel einbinden: https://github.com/HM-RedMatic/RedMatic/wiki/Homekit#tasten

**Comment by FuggyD** [comment]
Kleiner Schlussvermerk:
Mein HM-PBI-4-FM hat nicht den Event PRESS_SHORT gesendet sondern INSTALL_TEST, daher hat auch mein Script nicht funktioniert.
Bis ich herausgefunden habe warum der Sender INSTALL_TEST schickt anstelle von PRESS_SHORT werde ich den Trigger auf INSTALL_TEST laufen lassen.
kann wieder geclosed werden.

**Comment by Sineos** [comment]
@FuggyD schalte die Verschlüsselung für den Kanal ab, dann sollte es funktionieren.

**Comment by FuggyD** [comment]
Danke. Kanal war gesichert, hab ihn auf Standard gesetzt und nun kommt auch PRESS_SHORT.
