### ISSUE TITLE
DeviceName von einer CCU Node kann nicht mehr angezeigt werden bzw benutzt werden

### ISSUE THREAD

**Issue by Revilo91** [HM-RedMatic/RedMatic#115]
Hallo zusammen,
ich habe sei dem Update auf die RedNode-Version v1.10.0 keinen Zugriff mehr auf die Eigenschaft "deviceName" von einer CCU-Node. Liegt es vielleicht an der falschen Version [node-red-contrib-ccu (1.10.3)]

Vielen Dank für jede Hilfestellung.

Mit freundlichen Grüßen
Olli

**Comment by hobbyquaker** [comment]
Benötige hier noch mehr Infos, wo genau fehlt der deviceName? In den Messages oder in einer Node-Configuration? Welche Nodes sind betroffen - rpc event? value?

**Comment by Revilo91** [comment]
Ich brauch diese Eigenschaft, um mit dem Namen ein globales Context abzuspeichern (um danach mit dieser "Variable" weiterzuarbeiten.

> In den Messages oder in einer Node-Configuration? 
Könntest du das mir vielleicht ein bisschen genauer erklären, was du damit meinst?

> Welche Nodes sind betroffen - rpc event? value?
Es sind die rpc events betroffen.

![image](https://user-images.githubusercontent.com/39066472/50376113-003d4b00-0609-11e9-8862-7a909769d20a.png)
(Was auch noch auffällig ist, dass die Nodes nur partly connected sind)

Hier wäre der Beispielflow:
`[{"id":"5d9be973.583b68","type":"ccu-value","z":"e6322c3c.5ca3","name":"","iface":"BidCos-RF","channel":"LEQ1175017:1 SZ_Oliver_FK:1","datapoint":"STATE","mode":"","start":true,"change":true,"cache":true,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"67c7693f.61fc28","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":560,"y":360,"wires":[["28d44aee.7f60c6"]]},{"id":"39b9616.7e9899e","type":"ui_text","z":"e6322c3c.5ca3","group":"5957694e.027658","order":1,"width":0,"height":0,"name":"","label":"Fenster Oliver","format":"{{msg.payload}}","layout":"row-spread","x":960,"y":360,"wires":[]},{"id":"28d44aee.7f60c6","type":"function","z":"e6322c3c.5ca3","name":"Fenster","func":"var o = msg.payload;\nvar newMsg;\nif (o){\n    newMsg = {payload: \"Offen\"};\n}\nelse{\n     newMsg = {payload:  \"Geschlossen\"};\n}\ncontext.global.set(msg.deviceName,o);\nreturn newMsg;","outputs":1,"noerr":0,"x":780,"y":360,"wires":[["39b9616.7e9899e"]]},{"id":"67c7693f.61fc28","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":false,"bcwiEnabled":false,"cuxdEnabled":true,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","contextStore":"default"},{"id":"5957694e.027658","type":"ui_group","z":"","name":"OG","tab":"d9240c04.bd50f","order":1,"disp":true,"width":"6","collapse":true},{"id":"d9240c04.bd50f","type":"ui_tab","z":"","name":"Sicherheit","icon":"lock","order":3}]`

Ich hoffe, dass ich dir damit jetzt besser helfen konnte :)

**Comment by Revilo91** [comment]
Hab "Redmatic" auf Version "1.10.2" und "node-red-contrib-ccu" auf Version "1.10.5" geupdatet. Der rpc event zeigt jetzt connected an, nur leider komme ich immer noch nicht auf diese Eigenschaft.

Hier wäre auch mal ein Log, vielleicht hilft dir das noch ein bisschen weiter (vielleicht hab ich dir ja was unterschlagen)
[redmatic.2018-12-23T13_56_07.947Z.log](https://github.com/HM-RedMatic/RedMatic/files/2706012/redmatic.2018-12-23T13_56_07.947Z.log)


Vielen Dank für deinen Support in der Weihnachtszeit, ist ja auch nicht selbstverständlich!

**Comment by hobbyquaker** [comment]
Das Log sieht seltsam aus. Ist voll mit HTML Fragmente, kein blassen schimmer wie die da hingekommen sind :D Führt mich allerdings zu der Befürchtung dass Deine RedMatic Installation irgendwie "kaputt" ist. Ich würde empfehlen mal die Flows zu sichern, das RedMatic Addon komplett zu deinstallieren, CCU Rebooten, sicherstellen dass das Verzeichnis `/usr/local/addons/redmatic` wirklich weg ist und es dann nochmal neu zu installieren und die Flows wieder zurückzuspielen.

**Comment by Revilo91** [comment]
... Nicht Wirklich... der einfachste Fall hat geholfen.. 

**AEG** (Ausschalten, Einschalten, Geht)... 

Ich habe die Redmatic einfach mal gestoppt - gewartet - und wieder gestartet. Tadaaaa sie läuft wieder und ich kann auf die Eigenschaft wieder zugreifen. 
Komischerweise habe ich die Redmatic davor auf die 1.10.2 geupdated und einen Neustart durchgeführt,  danach ging es aber irgendwie trotzdem nicht... Naja, funktioniert ja jetzt wieder!


Erstmal vielen Dank für den superschnellen Support und bitte mach weiter so hobbyquaker! Dieses Projekt ist echt der Hammer!
