### ISSUE TITLE
Bilder für Wiki

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic#119]
<img width="506" alt="bildschirmfoto 2018-12-26 um 21 29 50" src="https://user-images.githubusercontent.com/44581521/50490569-0fa80400-0a0e-11e9-9366-67812dc30daf.png">
<img width="695" alt="bildschirmfoto 2018-12-26 um 21 30 22" src="https://user-images.githubusercontent.com/44581521/50490572-12a2f480-0a0e-11e9-87a5-598a16008ffc.png">
<img width="497" alt="bildschirmfoto 2018-12-26 um 21 30 40" src="https://user-images.githubusercontent.com/44581521/50490575-15054e80-0a0e-11e9-8eb3-f8f4586a172d.png">
![Uploading Bildschirmfoto 2018-12-26 um 21.31.07.png…]()

**Comment by drMaxxi** [comment]
<img width="497" alt="bildschirmfoto 2018-12-26 um 21 31 07" src="https://user-images.githubusercontent.com/44581521/50490693-bab8bd80-0a0e-11e9-98a8-52f478a31271.png">

**Comment by Hypnos3** [comment]
Du musst den issue nicht speichern. Einfach auf neuen issue geheb, Bilder rinkopieren, link rauskopieren, ohne speichern Tab schließen.
