### ISSUE TITLE
node-red-contrib-amazondash

### ISSUE THREAD

**Issue by Christoph22** [HM-RedMatic/RedMatic#124]
Ich würde gerne Amazon DashButtons in RedMatic nutzen

`# dependancy on libpcap for reading packets`
`$ sudo apt-get install libpcap-dev`
`npm install node-red-contrib-amazondash`

**Comment by hobbyquaker** [comment]
Problem dabei: dafür muss sich RedMatic im gleichen WLAN befinden wie die Dashbuttons. Eine CCU3 unterstützt aber gar kein WLAN. Ich überleg mal wie man das angehen könnte, müsste eine Fallunterscheidung her die RaspberryMatic und CCU3 hier gesondert behandelt. 
Related: #93

**Comment by dehsgr** [comment]
@hobbyquaker bei homebridge gibt es ein Plugin (homebridge-amazondash), bei dem es auch ohne WLAN funktioniert (bei mir zumindest). Ggf. hilft das ja weiter.

**Comment by hobbyquaker** [comment]
Hier gibt es einen Flow der das ganz ohne die Installation zusätzlicher Nodes bewerkstelligt: https://github.com/holgerimbery/redmatic_flows/blob/master/dashbutton_auswerten/dashbutton.md

**Comment by holgerimbery** [comment]
@Christoph22: Das geht alles auch ohne zusätzliche nodes, mit RedMatic (node-red) Boardmittel hat man bereits alles was man braucht. Mit einem "UDP input node" und einem function node kann man sich einen einfachen sub-flow bauen und diesen dann nutzen, habe das wiki ergänzt.
Natürlich alles mit "works on my machine" disclaimer :-)

**Comment by Christoph22** [comment]
@hobbyquaker @holgerimbery Danke, perfekte Lösung ohne irgendwelche zusätzlichen Nodes
