### ISSUE TITLE
HomeKit fehlerhaft?

### ISSUE THREAD

**Issue by TAOGde** [HM-RedMatic/RedMatic#125]
Hallo Hobbyquaker. 

Vielen Dank für RedMatic.  Meine Freundin fühlt sich etwas verlassen 😂😂 aber alles gut. 

Ich habe heute versucht HomeKit einzubinden. 
Ich bekomme den Fehler das die Bridge aktuell nicht unterstützt wird. 

Habe in der Recherche noch nichts nützliches gefunden. Oder nicht ordentlich gesucht. 
Kannst du mir dazu was sagen?

Edit: Hängt das auch mit diesem Fehler vielleicht zusammen? Der Log ist beim installieren von einem node ([https://flows.nodered.org/node/node-red-contrib-homekit-bridged](url)) entstanden:
`> curve25519-n@1.4.0 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-homekit/node_modules/curve25519-n
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at...
`

![fullsizeoutput_a42](https://user-images.githubusercontent.com/43980652/50557518-5172cc00-0ce6-11e9-9479-0cbb35d69f2a.jpeg)
![fullsizeoutput_a41](https://user-images.githubusercontent.com/43980652/50557525-664f5f80-0ce6-11e9-8452-7e57c4e7c620.jpeg)

**Comment by hobbyquaker** [comment]
Das nachinstallieren node-red-contrib-homekit-bridged kann nicht funktionieren und ist auch nicht notwendig, RedMatic liefert bereits alles mit was Du für HomeKit brauchst. Warum die Bridge nun als "nicht unterstützt" gezeigt wird kann ich so nicht sagen, da muss ich ein Blick auf Deine Logs werfen (kannst im CCU WebUI -> Systemsteuerung -> RedMatic -> Log herunterladen).

**Comment by TAOGde** [comment]
Habe ich dir mal eingefügt.


`{
   "ccu": {
      "VERSION": "3.41.11",
      "PRODUCT": "ccu3",
      "PLATFORM": "rpi3"
   },
   "redmatic": "1.10.9",
   "nodejs": "8.14.1",
   "ain2": "3.0.0",
   "node-red": "0.19.5",
   "node-red-node-serialport": "0.6.8",
   "node-red-node-sqlite": "0.3.6",
   "npm": "6.5.0",
   "node-red-contrib-ccu": "1.10.9",
   "node-red-contrib-combine": "1.6.2",
   "node-red-contrib-cpu": "0.0.4",
   "node-red-contrib-dashboard-average-bars": "0.0.6",
   "node-red-contrib-dwd": "0.9.0",
   "node-red-contrib-flightradar24": "0.0.6",
   "node-red-contrib-huemagic": "1.9.0",
   "node-red-contrib-moment": "3.0.1",
   "node-red-contrib-mqtt-json": "1.0.1",
   "node-red-contrib-os": "0.1.7",
   "node-red-contrib-pid": "1.1.4",
   "node-red-contrib-sun-position": "0.1.16",
   "node-red-contrib-time-range-switch": "0.6.1",
   "node-red-dashboard": "2.13.0",
   "node-red-node-email": "1.0.7",
   "node-red-node-instagram": "0.1.0",
   "node-red-node-openweathermap": "0.2.1",
   "node-red-node-rbe": "0.2.4",
   "node-red-node-strava": "0.1.0",
   "redmatic-homekit": "1.2.1",
   "redmatic-led": "1.0.0",
   "redmatic-webapp": "0.2.1"
}
Dec 31 11:07:14 Smarthome-CCU3 daemon.info node-red[693]: Settings file  : /usr/local/addons/redmatic/lib/settings.js
Dec 31 11:07:14 Smarthome-CCU3 daemon.info node-red[693]: Context store  : 'default' [module=localfilesystem]
Dec 31 11:07:14 Smarthome-CCU3 daemon.info node-red[693]: User directory : /usr/local/addons/redmatic/var
Dec 31 11:07:14 Smarthome-CCU3 daemon.warn node-red[693]: Projects disabled : editorTheme.projects.enabled=false
Dec 31 11:07:14 Smarthome-CCU3 daemon.info node-red[693]: Flows file     : /usr/local/addons/redmatic/var/flows.json
Dec 31 11:07:14 Smarthome-CCU3 daemon.info node-red[693]: Server now running at http://127.0.0.1:1880/addons/red/
Dec 31 11:07:14 Smarthome-CCU3 daemon.info node-red[693]: Starting flows
Dec 31 11:07:15 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] paramsets loaded from /usr/local/addons/redmatic/var/ccu_paramsets_v2.json
Dec 31 11:07:15 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] metadata loaded from /usr/local/addons/redmatic/var/ccu_192.168.123.111.json
Dec 31 11:07:16 Smarthome-CCU3 daemon.info node-red[693]: Started flows
Dec 31 11:07:18 Smarthome-CCU3 daemon.info node-red[693]: [redmatic-homekit-bridge:Bridge RedMatic] published bridge (0 Accessories) Bridge RedMatic CC:22:3D:CF:3D:1D on port 51826
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices, CUxD
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] ReGaHSS http port 1999 connected
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] xmlrpc server listening on http://192.168.123.111:2059
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] init BidCos-RF http://192.168.123.111:2059 nr_f36b_BidCos-RF
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] init HmIP-RF http://192.168.123.111:2059 nr_bd68_HmIP-RF
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] init VirtualDevices http://192.168.123.111:2059 nr_e199_VirtualDevices
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] binrpc server listening on binrpc://192.168.123.111:2058
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] init CUxD binrpc://192.168.123.111:2058 nr_a4f4_CUxD
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] CUxD binrpc port 8701 connected
Dec 31 11:07:21 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] HmIP-RF http port 2010 connected
Dec 31 11:07:22 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] metadata saved to /usr/local/addons/redmatic/var/ccu_192.168.123.111.json
Dec 31 11:07:22 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] BidCos-RF http port 2001 connected
Dec 31 11:07:31 Smarthome-CCU3 daemon.info node-red[693]: [ccu-connection:Raspi CCU3] VirtualDevices http port 9292 connected
Dec 31 11:11:11 Smarthome-CCU3 daemon.info node-red[693]: Installing module: node-red-contrib-homekit-bridged, version: 0.3.6
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: Installation of module node-red-contrib-homekit-bridged failed:
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: ------------------------------------------
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: > curve25519-n@1.4.0 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-homekit-bridged/node_modules/curve25519-n
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: > node-gyp rebuild
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! configure error 
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:89:16
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/index.js:42:5
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! System Linux 4.14.79-v7+
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-homekit-bridged/node_modules/curve25519-n
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! node -v v8.14.1
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! node-gyp -v v3.8.0
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: gyp ERR! not ok 
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm WARN node-red-project@0.0.1 No repository field.
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm WARN node-red-project@0.0.1 No license field.
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! code ELIFECYCLE
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! errno 1
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! Exit status 1
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! 
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! Failed at the curve25519-n@1.4.0 install script.
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR! A complete log of this run can be found in:
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: npm ERR!     /usr/local/addons/redmatic/npm-cache/_logs/2018-12-31T10_11_32_557Z-debug.log
Dec 31 11:11:32 Smarthome-CCU3 daemon.warn node-red[693]: ------------------------------------------`

**Comment by TAOGde** [comment]
Ich habe einen nicht sichtbaren Flow wo ich alle Bridges eingetragen habe die ich nutze.
Den Code kann ich in der Homeapp auch einscannen und das klappt ohne Fehler.
<img width="1116" alt="bildschirmfoto 2018-12-31 um 11 28 25" src="https://user-images.githubusercontent.com/43980652/50558499-43757900-0cef-11e9-82da-0b12226ddee7.png">

**Comment by hobbyquaker** [comment]
Der Flow "Geräte und Bridges" auf dem Screenshort ist deaktiviert - damit werden die Nodes in diesem Flow nicht gestartet. 

Und was verbirgt sich hinter dem Node "Keller"? Ist das auch ein "HomeKit Homematic" Node? Davon sollte es nur einen je Bridge-Config geben, mehrere zu nutzen ist nur dann notwendig wenn man über 100 Accessories in HomeKit bereitstellen will.

**Comment by TAOGde** [comment]
Im Keller sind nur zwei Werte aus der CCU für Temperatur und Feuchtigkeit.
Ich teste mal das einfügen der Bridge in einen aktiven Flow. Das war mir so noch nicht bewusst.

**Comment by hobbyquaker** [comment]
Nochmal wegen dem "Keller" Node: Ist das ein "HomeKit Homematic Node"? Davon darf es je Bridge nur einen geben.

**Comment by TAOGde** [comment]
> Ist das auch ein "HomeKit Homematic" Node?

Achso, das ist meine WansView Überwachungskamera, sprich Camera-ffmpeg.
