### ISSUE TITLE
hm-rpc nicht mehr erreichbar nach update auf 3.41.11

### ISSUE THREAD

**Issue by dilmash** [HM-RedMatic/RedMatic#129]
Nach der Installation der Version 3.41.11 auf einen raspi3+ erreiche ich die rpc schnittstelle nicht mehr weder über iobroker (init: response timeout) noch über meine iOS App  @Home. In den Firewalleinstellungen sind alle ports offen (Test), RPC und Script API auf Vollzugriff.  Zusätzlich sind installiert CUxDaemon und RedMatic
Was habe ich übersehen?

**Comment by hobbyquaker** [comment]
Auch wenn das überhaupt nichts mit RedMatic zu tun hat ... ;-)

> Was habe ich übersehen?

* https://forum.iobroker.net/viewtopic.php?t=19256
* https://homematic-forum.de/forum/viewtopic.php?f=53&t=17891&start=180#p478205
