### ISSUE TITLE
Fehlermeldung beim Ansprechen des HmIP-PCBS

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic#130]
Wenn ich mittels des Tasters HM-RC-4-3 den HmIP-PCBS für 250ms auf ein schalten will (als Türöffner), dann werden im debug-Fenster folgende Fehler angezeigt:

unknown subtype localhost

< HmIP-RF setValue Error: XML-RPC fault: Generic error (TIMEOUT)

rpc > HmIP-RF setValue ["000458A9961401:3","STATE",true] < Error: XML-RPC fault: Generic error (TIMEOUT)

rpc > HmIP-RF setValue ["000458A9961401:3","STATE",true] < Error: Unexpected endLine: 0Column: 0Char: 

< HmIP-RF setValue Error: Unexpected endLine: 0Column: 0Char:

**Comment by hobbyquaker** [comment]
Das ist ein Fehler (`Generic error (TIMEOUT)`) der vom Schnittstellenprozess (hmipserver) generiert wird, da kann RedMatic nichts dran drehen. Warum der kommt kann ich Dir nicht sagen, kann verschiedene Ursachen haben, die trivialste ist dass der Aktor schlicht nicht per Funk erreichbar ist.
