### ISSUE TITLE
Mehrere Bridges

### ISSUE THREAD

**Issue by habeck76** [HM-RedMatic/RedMatic#133]
Hallo, ich benötige bitte Hilfe. Aktuell habe ich 2 Bridges im Homekit die super funktionieren. Sobald ich eine dritte im Flow konfiguriere, funktioniert plötzlich nur noch eine. Im Log kann man sehen, dass alle Geräte den Bridges hinzugefügt werden aber nicht für alle erfolgt ein publish. Es läuft nur noch die  Bridge, die in der Homekit App den Standort Pfeil hat. Habe das jetzt mehrfach getestet und bekomme das leider nicht hin. Alle Bridges haben separates Port + MAC. Testweise nur ein Gerät zugewiesen. Danke für Eure Hilfe!

**Comment by habeck76** [comment]
Siehe Logfile:

[redmatic.2019-01-08T09_37_32.434Z.log](https://github.com/HM-RedMatic/RedMatic/files/2736219/redmatic.2019-01-08T09_37_32.434Z.log)

**Comment by hobbyquaker** [comment]
Duplicate https://github.com/HM-RedMatic/RedMatic-HomeKit/issues/105
