### ISSUE TITLE
set value ==> CUxD im Interface DropDown nicht anwählbar

### ISSUE THREAD

**Issue by mcbo007** [HM-RedMatic/RedMatic#136]
Ich kann bei "set value" das "CUxD" Interface im DropDown Menü nicht selektieren.

Meine aktuelle RedMatic-Version ist 2.0.2.
Das Problem bestand aber auch mit Version 1.10.12.

Muss der Zugriff auf CUxD irgendwo aktiviert werden?

Gruß

Marcel

**Comment by hobbyquaker** [comment]
CUxD muss im CCU Connection Node aktiviert werden. Siehe https://github.com/HM-RedMatic/RedMatic/wiki/CCU-Nodes#ccu-connection-node
