### ISSUE TITLE
Debug-Info wird unter HTTPs nicht ausgegeben

### ISSUE THREAD

**Issue by dehsgr** [HM-RedMatic/RedMatic#137]
Schritte zur Reproduktion:
- RedMatic via HTTPs öffnen.
- Einen Inject-Node anlegen.
- Einen Debug-Node anlegen (Full msg).
- Beide Nodes verbinden.
- Deploy durchführen.
- Auf Debug-View umstellen.
- Inject durchführen.

Ist-Zustand:
- Kein Debug-Output

Soll-Zustand:
- Debug-Output

Zusätzliche Informationen:
- Aktueller Safari unter aktuellen macOS
- Unter Verwendung von HTTP erfolgt der Debug-Output.

**Comment by ptweety** [comment]
Solche Aussetzer habe ich nur bei alten Sessions mit Nodered, wenn z.B. ich am folgenden Tag weiter basteln wollte. Ansonsten kann ich es auch nicht bestätigen.

**Comment by drMaxxi** [comment]
Ebenso wie bei ptweety: Seite schließn u d wieder öffnen, dann passts wieder.

**Comment by dehsgr** [comment]
Okay. Das kann ich bestätigen. In diesem Sinne mache ich hier mal wieder dicht. Danke für den Workaround auf den ich hätte auch selbst mal kommen können. ;-)
