### ISSUE TITLE
Verbindung remote Node Red Instanz

### ISSUE THREAD

**Issue by emeins** [HM-RedMatic/RedMatic#141]
Hallo,
ich möchte meine bestehende Node Red Installation mit HomeMatic verbinden (also nicht die integrierte RedMatic Instanz). Folgende Umgebung:

- HomeMatic auf Raspi als piVCCU (v3.41.11) + RedMatic v2.3.0,  XML-API v1.20, CUxD v2.2.0, Security (Firewall etc.) auf der HomeMatic ist aus meiner Sicht voll deaktiviert.

- Node Red auf Hostsystem der piVCCU, v0.19.5, incl. node-red-contrib-ccu v1.11.2

Leider läuft die Verbindung nicht. Das Auswahlfeld "Interface" im Edit value node ist auch deaktiviert (sowohl bei aktivierter als auch deaktivierter CUxD Option).

Im RedNode Log sehe ich nur eine Fehlermeldung "node: piVCCU msg : error "TypeError: Cannot convert undefined or null to object"".

Die NodeRed Instanz direkt auf der HomeMatic funktioniert.

![image](https://user-images.githubusercontent.com/17033201/51732248-fda59980-207d-11e9-83eb-2a88bee6052b.png)

![image](https://user-images.githubusercontent.com/17033201/51732267-07c79800-207e-11e9-968e-4c45a56ad0ba.png)

**Comment by EdgarM73** [comment]
Hi emeins,

hatte ein ähnliches Problem, bei mir lag es an den beiden Ports 3047/3048 und dass sie in der Firewall ( bei mir in den Docker Ports ) nicht freigeschaltet waren.

**Comment by emeins** [comment]
Danke Edgar, ich hatte verstanden, dass die Ports nur für die Rückkommunikation der Events benötigt werden. Bei mir läuft auch keine Docker Umgebung.

**Comment by EdgarM73** [comment]
In der CCU gibt es eine Firewall, ich würde dort mal versuchen die Ports zu öffnen.

**Comment by emeins** [comment]
ist alles offen - "Vollzugriff"

**Comment by emeins** [comment]
Ohh Mann, anscheinend liegt es an der Node Red Version, die man als Adapter im ioBroker installieren kann. Das ist zwar vom Versionsstand die Gleiche, aber scheinbar doch irgenwie anders...
Jetzt hab ich NR noch mal seperat installiert und läuft sauber.
Ggf. auch ein Language-Thema? In den Screenshots oben (vom ioBroker NR Adapter) waren die Statements in Englisch, bei meiner Installation jetzt sind sie in Deutsch - nur eine Vermutung.
![image](https://user-images.githubusercontent.com/17033201/51760993-2b193400-20cc-11e9-93b7-98d8af25ffd1.png)
