### ISSUE TITLE
Python-Fehler beim Installieren des Moduls "Smartmeter"

### ISSUE THREAD

**Issue by m50434** [HM-RedMatic/RedMatic#144]
Hi,
leider kann ich das Modul "Smartmeter" in Node-Red nicht installieren. Hiermit wollte ich meinen Heizungszähler auslesen (das klappt auf einem anderen System mit IoBroker und Node-Red auch schon hervorragend).

Folgende Fehlermeldung kommt beim Installations-Versuch:
```
serialport@6.2.2 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-smartmeter/node_modules/serialport
 prebuild-install || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=10.15.0 runtime=node arch=arm platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:...
```
Wenn ich es richtig verstehe, fehlt Python auf dem Raspmatic?!

Kann mir jemand helfen?!

Danke!

**Comment by hobbyquaker** [comment]
node-red-contrib-smartmeter nutzt node-serialport, das benötigt Binärmodule, das kann auf RaspberryMatic/CCU3 nicht gebaut werden. Ich werd es ins nächste Release mit aufnehmen.

**Comment by hobbyquaker** [comment]
"asap" ;-)

**Comment by hobbyquaker** [comment]
@m50434 habe node-red-contrib-smartmeter in RedMatic v2.4.0 integriert. Bitte gib Bescheid ob es funktioniert.

**Comment by m50434** [comment]
Perfekt. Danke. Habs auch mit einem IO-Reader getestet und läuft!
