### ISSUE TITLE
HM-PBI-4-FM - falsche Datenpoints

### ISSUE THREAD

**Issue by taucher4000** [HM-RedMatic/RedMatic#145]
Hallo, ich habe mir gerade zwei HM-PBI-4-FM (4-Fach Tasterschnitstelle) eingebaut und wollte den Tastendruck (PRESS_SHORT und PRESS_LONG) via RedMatic nutzen. Allerdings reagiert Redmatic auf die Datenpunkte PRESS_SHORT und PRESS_LONG nicht sondern. Stattdessen wird der Datenpunkt INSTALL_TEST getriggert. in der CCU selber wird ein PRESS_LONG und PRESS_SHORT ordnungsgemäß erkannt.

Kann man das irgend wie anpassen?

Gruß
Taucher

**Comment by hobbyquaker** [comment]
Schalte mal die gesicherte Übertragung für das Gerät aus und leg ein Programm in der CCU an das durch den Tastendruck getriggert wird (egal ob kurz oder lang) und nichts macht. Siehe dazu auch https://github.com/jens-maus/RaspberryMatic/issues/399 und https://github.com/HM-RedMatic/RedMatic/issues/61

**Comment by taucher4000** [comment]
Es hat schon gereicht, die gesicherte Übertragung zu deaktivieren. Das Dummy-Programm war nicht nötig. Vielen Dank für die schnelle Antwort. Problem gelöst!

**Comment by jensemannn** [comment]
Wie schaltet man die gesicherte Übertragung für einen HM-PBI-4-FM aus?
