### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic#147]
Ich habe folgenden Flow erstellt um das Temperaturminimum der letzten 24h in einer CCU3 Variable abzulegen. Das komische ist, dass es manchmal funktioniert und manchmal wird der Wert "true" in die Homematic Variable geschrieben (wenn wo ein Fehler wäre, würde ich mir immer das gleiche Problem erwarten).

Screenshot:
<img width="994" alt="bildschirmfoto 2019-02-03 um 09 54 58" src="https://user-images.githubusercontent.com/44581521/52174835-4229e700-279a-11e9-91e5-923e049f09cc.png">

`[{"id":"785580f1.4e8cf8","type":"ccu-value","z":"7814b12f.c955e8","name":"","iface":"HmIP-RF","channel":"001858A98C1920:1 WS:1 Statusmitteilung Wetterdaten","datapoint":"ACTUAL_TEMPERATURE","mode":"","start":true,"change":true,"cache":true,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":760,"wires":[["7160b761.9bd67"]]},{"id":"7160b761.9bd67","type":"switch","z":"7814b12f.c955e8","name":"global.wettertempmin","property":"payload","propertyType":"msg","rules":[{"t":"lt","v":"wettertempmin","vt":"global"}],"checkall":"true","repair":false,"outputs":1,"x":420,"y":760,"wires":[["df156dde.de34d"]]},{"id":"b677bca8.7e28e8","type":"ccu-sysvar","z":"7814b12f.c955e8","name":"Wetter.Temp.Min","ccuConfig":"38263145.35ea0e","topic":"ReGaHSS/${Name}","change":true,"cache":true,"x":890,"y":740,"wires":[[]]},{"id":"df156dde.de34d","type":"change","z":"7814b12f.c955e8","name":"set global.wettertempmin","rules":[{"t":"set","p":"wettertempmin","pt":"global","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":670,"y":760,"wires":[["b677bca8.7e28e8"]]},{"id":"aa0efa14.b91bc","type":"change","z":"7814b12f.c955e8","name":"set global.wettertempmin","rules":[{"t":"set","p":"wettertempmin","pt":"global","to":"99","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":670,"y":720,"wires":[["b677bca8.7e28e8"]]},{"id":"fcc03a8a.3c957","type":"time-inject","z":"7814b12f.c955e8","name":"reset:23.00","positionConfig":"82556fec.9a83b8","payload":"99","payloadType":"num","payloadTimeFormat":0,"payloadOffset":0,"payloadOffsetMultiplier":60,"payloadDays":"*","topic":"","time":"23:00","timeType":"entered","timeDays":"*","offset":0,"offsetMultiplier":60,"property":"","propertyType":"none","timeAlt":"","timeAltType":"entered","timeAltOffset":0,"timeAltOffsetMultiplier":60,"once":false,"onceDelay":0.1,"addPayload1":"","addPayload1Type":"none","addPayload1Value":"","addPayload1ValueType":"date","addPayload1Format":0,"addPayload1Offset":0,"addPayload1OffsetMultiplier":60,"addPayload1Days":"*","addPayload2":"","addPayload2Type":"none","addPayload2Value":"","addPayload2ValueType":"date","addPayload2Format":0,"addPayload2Offset":0,"addPayload2OffsetMultiplier":60,"addPayload2Days":"*","addPayload3":"","addPayload3Type":"none","addPayload3Value":"","addPayload3ValueType":"date","addPayload3Format":0,"addPayload3Offset":0,"addPayload3OffsetMultiplier":60,"addPayload3Days":"*","recalcTime":2,"x":480,"y":720,"wires":[["aa0efa14.b91bc"]]},{"id":"5e3e7309.8f4ae4","type":"comment","z":"7814b12f.c955e8","name":"Temp Min 24h","info":"","x":90,"y":720,"wires":[]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"CCU Wohnung","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","contextStore":""},{"id":"82556fec.9a83b8","type":"position-config","z":"","name":"Klobenstein (Ritten)","longitude":"11.458333","latitude":"46.541667","angleType":"deg","timezoneOffset":"1"}]`

**Comment by hobbyquaker** [comment]
Der Flow sieht auf den ersten Blick korrekt aus, kann mir im Moment nicht erklären woher da das `true` kommt, könnte also durchaus ein Bug sein. Muss ich weiter untersuchen.

**Comment by drMaxxi** [comment]
Danke. Habe dasselbe Problem auch bei anderen, ähnlichen Flows (z.B. Maximaltemperatur, Min-Max. Windrichtung, etc.)

**Comment by hobbyquaker** [comment]
Könntest Du mal versuchen so eine Nachricht wo der payload fälschlicherweise true ist mit einem Debug Node "aufzufangen" (complete msg object loggen und dann aus dem Debug Tab rauskopieren)?

**Comment by drMaxxi** [comment]
Das Problem ist, dass wenn ich daran herumbastele es keine Probleme gibt. Die treten erst auf, wenn es eine Weile läuft. Hier ist der Log 
`{"topic":"msg.payload","payload":0.5,"ccu":"localhost","iface":"HmIP-RF","device":"001858A98C1920","deviceName":"Wetterstation","deviceType":"HmIP-SWO-PR","channel":"001858A98C1920:1","channelName":"WS:1 Statusmitteilung Wetterdaten","channelType":"WEATHER_TRANSMIT","channelIndex":1,"datapoint":"ACTUAL_TEMPERATURE","datapointName":"HmIP-RF.001858A98C1920:1.ACTUAL_TEMPERATURE","datapointType":"FLOAT","datapointMin":-3276.8,"datapointMax":3276.7,"datapointDefault":0,"datapointControl":"WEATHER_TRANSMIT.ACTUAL_TEMPERATURE","value":0.5,"valueStable":0.5,"rooms":["Garten"],"room":"Garten","functions":["Wetter"],"function":"Wetter","ts":1549204450000,"lc":1549204450000,"change":false,"cache":true,"working":false,"stable":true,"_msgid":"2a5ca87a.270d98"}`

Das Log kommt übrigens aus dem switch node.

**Comment by drMaxxi** [comment]
Und dies ist das Log nach dem change node (vor dem edit sysvar node):

`{"topic":"msg.payload","payload":0.5,"ccu":"localhost","iface":"HmIP-RF","device":"001858A98C1920","deviceName":"Wetterstation","deviceType":"HmIP-SWO-PR","channel":"001858A98C1920:1","channelName":"WS:1 Statusmitteilung Wetterdaten","channelType":"WEATHER_TRANSMIT","channelIndex":1,"datapoint":"ACTUAL_TEMPERATURE","datapointName":"HmIP-RF.001858A98C1920:1.ACTUAL_TEMPERATURE","datapointType":"FLOAT","datapointMin":-3276.8,"datapointMax":3276.7,"datapointDefault":0,"datapointControl":"WEATHER_TRANSMIT.ACTUAL_TEMPERATURE","value":0.5,"valueStable":0.5,"rooms":["Garten"],"room":"Garten","functions":["Wetter"],"function":"Wetter","ts":1549204782000,"lc":1549204782000,"change":false,"cache":true,"working":false,"stable":true,"_msgid":"b80aa91b.335c78"}`

**Comment by drMaxxi** [comment]
Hast du in einem der letzten Updates etwas geändert, das dieses Problem beeinflussen könnte? Hab zufällig den Flow angeschaut und das "true" ist weg und Zahlen (die übrigens plausibel sind) werden angezeigt...

**Comment by hobbyquaker** [comment]
Könnte evtl. diese Änderung aus v2.5.0 gewesen sein:

 * Messages werden vor der Übergabe an einen Callback gecloned um Veränderungen des Zustands durch Nachfolgende Nodes zu verhindern ([f036018](https://github.com/HM-RedMatic/node-red-contrib-ccu/commit/f036018595865fdea8bf952527f2f2502b19ab74))

**Comment by drMaxxi** [comment]
Ja, diese Erklärung hört sich plausibel an.
