### ISSUE TITLE
"Emit only changed values" funktioniert nicht

### ISSUE THREAD

**Issue by vx-i** [HM-RedMatic/RedMatic#149]
Ich habe an meiner Sirene die Einstellung "Emit only changed values" aktiviert, wie unten im Bild zu sehen.

![grafik](https://user-images.githubusercontent.com/21290014/52178820-16772300-27d3-11e9-8e7e-a7612a23dc20.png)

Die CCU schickt ca. einmal die Stunde zyklische Statusmeldung. Diese werden von RedMatic automatisch durchgereicht, obwohl die Einstellung aktiv ist.

Deswegen habe ich Debug-Node mit der Sirene verbunden und abgewartet. Anbei drei Debug-Nachrichten.

3.2.2019, 15:43:21node: 7e0cb57a.88e04clocalhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE
```
{"topic":"localhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE",
"payload":1,
"ccu":"localhost",
"iface":"BidCos-RF",
"device":"NEQ0926815",
"deviceName":"Sirene_Flur",
"deviceType":"HM-Sec-Sir-WM",
"channel":"NEQ0926815:4",
"channelName":"Sirene_Flur_Scharf",
"channelType":"ARMING",
"channelIndex":4,
"datapoint":"ARMSTATE",
"datapointName":"BidCos-RF.NEQ0926815:4.ARMSTATE",
"datapointType":"ENUM",
"datapointMin":0,
"datapointMax":3,
"datapointDefault":0,
"datapointControl":"ARMING.ARMSTATE",
"value":1,
"valuePrevious":1,
"valueStable":1,
"rooms":["Flur"],
"room":"Flur",
"functions":["Sicherheit"],
"function":"Sicherheit",
"ts":1549205232724,
"tsPrevious":1549205000065,
"lc":1549205232724,
"change":true,
"cache":false,
"working":false,
"stable":true,
"_msgid":"e19584a7.f05d68"}
```

3.2.2019, 15:47:13node: 7e0cb57a.88e04clocalhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE
```
{"topic":"localhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE",
"payload":1,
"ccu":"localhost",
"iface":"BidCos-RF",
"device":"NEQ0926815",
"deviceName":"Sirene_Flur",
"deviceType":"HM-Sec-Sir-WM",
"channel":"NEQ0926815:4",
"channelName":"Sirene_Flur_Scharf",
"channelType":"ARMING",
"channelIndex":4,
"datapoint":"ARMSTATE",
"datapointName":"BidCos-RF.NEQ0926815:4.ARMSTATE",
"datapointType":"ENUM",
"datapointMin":0,
"datapointMax":3,
"datapointDefault":0,
"datapointControl":"ARMING.ARMSTATE",
"value":1,
"valuePrevious":0,
"valueStable":1,
"rooms":["Flur"],
"room":"Flur",
"functions":["Sicherheit"],
"function":"Sicherheit",
"ts":1549205000065,
"tsPrevious":1549204966265,
"lc":1549205000065,
"change":true,
"cache":false,
"working":false,
"stable":true,
"_msgid":"758e157e.1ef57c"}
```

3.2.2019, 16:42:24node: 7e0cb57a.88e04clocalhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE
```
{
	"topic": "localhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE",
	"payload": 1,
	"ccu": "localhost",
	"iface": "BidCos-RF",
	"device": "NEQ0926815",
	"deviceName": "Sirene_Flur",
	"deviceType": "HM-Sec-Sir-WM",
	"channel": "NEQ0926815:4",
	"channelName": "Sirene_Flur_Scharf",
	"channelType": "ARMING",
	"channelIndex": 4,
	"datapoint": "ARMSTATE",
	"datapointName": "BidCos-RF.NEQ0926815:4.ARMSTATE",
	"datapointType": "ENUM",
	"datapointMin": 0,
	"datapointMax": 3,
	"datapointDefault": 0,
	"datapointControl": "ARMING.ARMSTATE",
	"value": 1,
	"valuePrevious": 1,
	"valueStable": 1,
	"rooms": ["Flur"],
	"room": "Flur",
	"functions": ["Sicherheit"],
	"function": "Sicherheit",
	"ts": 1549208543876,
	"tsPrevious": 1549205232724,
	"lc": 1549208543876,
	"change": true,
	"cache": false,
	"working": false,
	"stable": true,
	"_msgid": "c06e6b45.1442d8"
}
```

Diese Werte sind besonders spannend.
`"ts":1549205232724,"value":1,"valuePrevious":1`
`"ts":1549205000065,"value":1,"valuePrevious":0,"tsPrevious":1549204966265,`
`"ts":1549208543876,"value":1,"valuePrevious":1,"tsPrevious":1549205232724`

Die Zeitstempel stimmen nicht überein und der Schlüssel "change" hat immer den Wert "true".

Ich würde gerne weitersuchen, weiß aber nicht wo. Könnte mir bitte jemand einen Hinweis geben?

**Comment by hobbyquaker** [comment]
Das sieht so aus als ob ich da ein Fehler beim Erkennen des "change" gemacht hab. Könntest Du mal den Haken bei "emit only changed values" entfernen und nochmal ein paar Nachrichten zur Ansicht liefern?

**Comment by vx-i** [comment]
So auf die Schnelle würde ich sagen, dass:

this.values[datapointName].payload !== payload

gegen

this.values[datapointName].***value*** !== payload

geändert werden muss.

**Comment by vx-i** [comment]
```
{
"topic":"localhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE",
"payload":1,
"ccu":"localhost",
"iface":"BidCos-RF",
"device":"NEQ0926815",
"deviceName":"Sirene_Flur",
"deviceType":"HM-Sec-Sir-WM",
"channel":"NEQ0926815:4",
"channelName":"Sirene_Flur_Scharf",
"channelType":"ARMING",
"channelIndex":4,"datapoint":"ARMSTATE",
"datapointName":"BidCos-RF.NEQ0926815:4.ARMSTATE",
"datapointType":"ENUM",
"datapointMin":0,
"datapointMax":3,
"datapointDefault":0,
"datapointControl":"ARMING.ARMSTATE",
"value":1,
"valuePrevious":1,
"valueStable":1,
"rooms":["Flur"],
"room":"Flur",
"functions":["Sicherheit"],
"function":"Sicherheit",
"ts":1549215250766,
"tsPrevious":1549211920000,
"lc":1549211920000,
"change":false,
"cache":false,
"working":false,
"stable":true,
"_msgid":"5b89ef74.d4251"
}
```

**Comment by vx-i** [comment]
```
{
"topic":"localhost/BidCos-RF/Sirene_Flur_Scharf/ARMSTATE",
"payload":1,
"ccu":"localhost",
"iface":"BidCos-RF",
"device":"NEQ0926815",
"deviceName":"Sirene_Flur",
"deviceType":"HM-Sec-Sir-WM",
"channel":"NEQ0926815:4",
"channelName":"Sirene_Flur_Scharf",
"channelType":"ARMING",
"channelIndex":4,
"datapoint":"ARMSTATE",
"datapointName":"BidCos-RF.NEQ0926815:4.ARMSTATE",
"datapointType":"ENUM",
"datapointMin":0,
"datapointMax":3,
"datapointDefault":0,
"datapointControl":"ARMING.ARMSTATE",
"value":1,
"valuePrevious":1,
"valueStable":1,
"rooms":["Flur"],
"room":"Flur",
"functions":["Sicherheit"],
"function":"Sicherheit",
"ts":1549218638506,
"tsPrevious":1549215250000,
"lc":1549215250000,
"change":false,
"cache":false,
"working":false,
"stable":true,
"_msgid":"b72b20dd.cd9ea"
}
```

**Comment by vx-i** [comment]
@hobbyquaker Ich habe gestern die oben genannte Änderung auf meinem Raspi gemacht und die Funktion "Emit only changed values" aktiviert. Das hat funktioniert. Nachrichten werden jetzt nur ausgelöst, wenn sich der Wert geändert hat.

**Comment by hobbyquaker** [comment]
Dass es an payload vs value hing kann eigentlich nicht sein, beide Properties enthalten immer das selbe. Hast Du bereits auf RedMatic 2.4.1 aktualisiert? Ich glaube nämlich das Problem entsteht an anderer Stelle, bei der Verarbeitung von "WORKING" Events die seit 2.4.1 auch beim Kanaltyp "ARMING" funktionieren sollte.

**Comment by hobbyquaker** [comment]
@vx-i check mal bitte ob das Problem in v2.5.0 (ohne die Änderung von `payload` in `value`) noch Auftritt.

**Comment by vx-i** [comment]
@hobbyquaker Guten Abend Sebastian! Die späte Antwort tut mir leid. Bin gerade beruflich ziemlich eingespannt. Es hat bereits mit Version 2.4.1 funktionert. Vielen Dank für deinen Support.
