### ISSUE TITLE
HmIP-ASIR lässt sich nicht ansteuern

### ISSUE THREAD

**Issue by CNpunkt** [HM-RedMatic/RedMatic#150]
Hallo zusammen,
ich habe versucht die Alarmsirene HmIP-ASIR ans laufen zu bekommen, leider ohne Erfolg.
Ich möchte anhand einer Variablenänderung auf der CCU die Sirene aktivieren.
Mir ist bewusst, dass bei der Sirene 4 Werte gesetzt werden müssen. Aus meiner Sicht ist dies in meinem Flow richtig:
![image](https://user-images.githubusercontent.com/16060613/52496460-a3571d80-2bd3-11e9-9f54-7ae01b0d7955.png)

Debuglog:
![image](https://user-images.githubusercontent.com/16060613/52496445-99cdb580-2bd3-11e9-935f-a7ddfe8183c8.png)

Hier noch der exportierte Flow:
[Flow.txt](https://github.com/HM-RedMatic/RedMatic/files/2847691/Flow.txt)

Leider rührt sich bei der Sirene nichts. Hat jemand von Euch eine Idee woran das liegen könnte?
[#49](https://github.com/HM-RedMatic/RedMatic-HomeKit/issues/49) hatte ich mir schon angesehen.

**Comment by hobbyquaker** [comment]
ich glaub das Problem sind die Payloads, Du nutzt die Enum Beschreibungen, versuche mal stattdessen die Werte zu setzen. Also statt `BLINKING_BOTH_REPEATING` die Number `2`, statt `DISABLE_ACOUSTIC_SIGNAL` die Number `0` und statt `S` auch die Number `0`.

**Comment by CNpunkt** [comment]
Klasse, das hat funktioniert. Vielen Dank!

**Comment by drMaxxi** [comment]
Hallo CNpunkt,

Könntest du bitte den funktionierenden Flow posten? Würde ihn gerne testen, vielen Dank!

**Comment by CNpunkt** [comment]
Klar, kein Thema.

`[{"id":"1f7958e.43e6ba7","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"48dd7616.f1c4f8","type":"change","z":"1f7958e.43e6ba7","name":"Gleichzeitiges schnelles blinken","rules":[{"t":"set","p":"payload","pt":"msg","to":"3","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":440,"wires":[["2920d0c0.eb0ee"]]},{"id":"2920d0c0.eb0ee","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"HmIP-RF","channel":"000AD8A990C8F0:3 Alarmsirene","datapoint":"OPTICAL_ALARM_SELECTION","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":590,"y":440,"wires":[[]]},{"id":"59fb4270.b3ad5c","type":"change","z":"1f7958e.43e6ba7","name":"Frequenz steigend","rules":[{"t":"set","p":"payload","pt":"msg","to":"1","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":500,"wires":[["830bf3e8.1da66"]]},{"id":"830bf3e8.1da66","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"HmIP-RF","channel":"000AD8A990C8F0:3 Alarmsirene","datapoint":"ACOUSTIC_ALARM_SELECTION","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":590,"y":500,"wires":[[]]},{"id":"dc635c0d.4a9e2","type":"change","z":"1f7958e.43e6ba7","name":"Sekunden Einheit","rules":[{"t":"set","p":"payload","pt":"msg","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":560,"wires":[["67a56872.342ac8"]]},{"id":"67a56872.342ac8","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"HmIP-RF","channel":"000AD8A990C8F0:3 Alarmsirene","datapoint":"DURATION_UNIT","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":590,"y":560,"wires":[[]]},{"id":"5ef74dcb.035144","type":"change","z":"1f7958e.43e6ba7","name":"300","rules":[{"t":"set","p":"payload","pt":"msg","to":"300","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":620,"wires":[["e6629dbe.7ae6d"]]},{"id":"e6629dbe.7ae6d","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"HmIP-RF","channel":"000AD8A990C8F0:3 Alarmsirene","datapoint":"DURATION_VALUE","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":590,"y":620,"wires":[[]]},{"id":"f0f49e90.d1308","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"HmIP-RF","channel":"000915699A465C:1 Bewegungsmelder Wohnzimmer","datapoint":"MOTION","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":250,"y":120,"wires":[["683db1e.ffde05"]]},{"id":"f648fbc1.c79e38","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"HmIP-RF","channel":"000917099A8CE8:1 Bewegungsmelder Flur","datapoint":"MOTION","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":230,"y":180,"wires":[["683db1e.ffde05"]]},{"id":"7fc854f3.689d2c","type":"ccu-rpc-event","z":"1f7958e.43e6ba7","name":"Fensterkontaktschalter prüfen","iface":"HmIP-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"","deviceRx":"str","deviceName":"","deviceNameRx":"str","deviceType":"HmIP-SWDO-I","deviceTypeRx":"str","channel":"","channelRx":"str","channelName":"","channelNameRx":"str","channelType":"","channelTypeRx":"str","datapoint":"STATE","datapointRx":"str","change":true,"working":false,"cache":false,"topic":"${CCU}/${Interface}/${channelName}/${datapoint}","x":240,"y":240,"wires":[["677bd83c.f95b08"]]},{"id":"683db1e.ffde05","type":"switch","z":"1f7958e.43e6ba7","name":"is true","property":"payload","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":650,"y":180,"wires":[["a98195f0.b88dc8"]]},{"id":"677bd83c.f95b08","type":"change","z":"1f7958e.43e6ba7","name":"1 --> true","rules":[{"t":"change","p":"payload","pt":"msg","from":"1","fromt":"num","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":460,"y":240,"wires":[["683db1e.ffde05"]]},{"id":"36cb62af.2fd76e","type":"switch","z":"1f7958e.43e6ba7","name":"is true","property":"payload","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":1070,"y":180,"wires":[["e0e8a8ff.6337a8"]]},{"id":"a98195f0.b88dc8","type":"ccu-get-value","z":"1f7958e.43e6ba7","name":"Alarmanlage eingeschaltet","ccuConfig":"38263145.35ea0e","iface":"ReGaHSS","channel":"","sysvar":"Alarmanlage eingeschaltet","sysvarProperty":"value","datapoint":"","datapointProperty":"value","setProp":"payload","setPropType":"msg","x":860,"y":180,"wires":[["36cb62af.2fd76e"]]},{"id":"e0e8a8ff.6337a8","type":"link out","z":"1f7958e.43e6ba7","name":"Alarmanlage Sirene auslösen","links":["b9bc3be1.f08888"],"x":1175,"y":180,"wires":[]},{"id":"b9bc3be1.f08888","type":"link in","z":"1f7958e.43e6ba7","name":"","links":["e0e8a8ff.6337a8"],"x":155,"y":520,"wires":[["48dd7616.f1c4f8","59fb4270.b3ad5c","dc635c0d.4a9e2","5ef74dcb.035144"]]},{"id":"57d6ac1d.ac5054","type":"comment","z":"1f7958e.43e6ba7","name":"Alarm auslösen","info":"","x":440,"y":380,"wires":[]},{"id":"362bb3b1.4c7b1c","type":"ccu-value","z":"1f7958e.43e6ba7","name":"","iface":"BidCos-RF","channel":"OEQ0351779:1 Haustürschloss","datapoint":"STATE","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":200,"y":300,"wires":[["683db1e.ffde05"]]},{"id":"3fabc73b.1cfac8","type":"comment","z":"1f7958e.43e6ba7","name":"Prüfung, ob ein Bewegungsmelder eine Bewegung erkannt hat, ein Fenster geöffnet oder die Haustür entriegelt wurde","info":"","x":600,"y":60,"wires":[]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""}]`

**Comment by drMaxxi** [comment]
Danke!

**Comment by hobbyquaker** [comment]
node-red-contrib-ccu unterstützt ab v1.15.0 die HmIP-ASIR im Signal Node

https://github.com/HM-RedMatic/node-red-contrib-ccu/issues/61

**Comment by FrankGiesecke** [comment]
Hat das Ganze schon mal Jemand über den "set value" Node als Multicast hinbekommen?
Mein Ziel ist es, mehrere HMIP-ASIR zeitgleich anzusteuern. Aktuell werden diese über den Signal Node nach einander ausgelöst.

Mit dem im Beispiel aufgezeigten Weg ist es zwar möglich, einzelne Sirenen anzusprechen, aber eine Adaptierung auf den "set value" Node ist mir bisher nicht gelungen.

/cc @CNpunkt
