### ISSUE TITLE
Dyson TP04

### ISSUE THREAD

**Issue by juppjuppsen** [HM-RedMatic/RedMatic#156]
Frage: kann sowas ohne großen Aufwand eingebunden werden?

https://www.npmjs.com/package/homebridge-dyson-link

**Comment by hobbyquaker** [comment]
Wenn Du Dein Dyson Gerät über Node-RED ansprechen kannst (keine Ahnung was das für ein API hat, vll reichen die HTTP Nodes dafür, vll müsste man spezielle Nodes nutzen/bauen...) dann kannst Du es über das "Universal Accessory" von RedMatic-HomeKit auch in HomeKit einbinden. Homebridge Plugins zu verwenden ist nicht vorgesehen.

**Comment by hobbyquaker** [comment]
Grade mal schnell gegoogled, diese lib https://github.com/auchenberg/dyson-purelink sieht ganz brauchbar aus, mit der könnte man mit relativ wenig Aufwand auch Node-RED Nodes bauen. Allerdings werd ich das (mangels eigenem Interesse) eher nicht tun ;-)

**Comment by juppjuppsen** [comment]
Wirklich sehr schade :-(
Eigentlich brauchst du aber eigentlich dringend einen high end Luftreiniger zu einem unverschämt günstigen Preis und musst den zufällig in deine Automatisierung einbinden, oder?

**Comment by hobbyquaker** [comment]
high end - unverschämt günstig - klingt interessant ;-)
