### ISSUE TITLE
Bug im time inject node oder in RaspberryMatic?

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic#157]
Einer meiner Raffstore wird anhand der Zeit des Sonnenaufgangs und Sonnenuntergangs gesteuert.. Allerdings funktioniert dies in letzter Zeit nicht mehr korrekt - leider kann ich nicht sagen seit welchem Update, da ich sowohl Raspberrymatic als auch RedMatic upgedated habe. Im  folgenden ein Screenshot der Fehlermeldung und einer der Einstellungen.

Laut debug-Melder ist die Fehlermeldung: "date.toLocaleTimeString is not a function"

<img width="299" alt="bildschirmfoto 2019-03-03 um 11 23 53" src="https://user-images.githubusercontent.com/44581521/53694138-94b2ef00-3daa-11e9-9fdc-3d6a3a1f54d0.png">
<img width="496" alt="bildschirmfoto 2019-03-03 um 11 24 39" src="https://user-images.githubusercontent.com/44581521/53694139-95e41c00-3daa-11e9-831c-ccc1fa8ce730.png"> 

Oder liegt der Fehler bei RaspberryMatic? https://github.com/jens-maus/RaspberryMatic/issues/565

**Comment by hobbyquaker** [comment]
Scheint ein Bug im time inject Node zu sein. @Hypnos3 kannst Du Dir das anschauen?

**Comment by Hypnos3** [comment]
ja, danke.
Schaue ich mir an.

**Comment by Hypnos3** [comment]
@drMaxxi: Ich konnte den Fehler leider nicht nachvollziehen.
Der Fehler sieht mir jedoch nach einem Problem aus, das in "node-red-contrib-sun-position | 0.2.2" vorhanden war (https://github.com/HM-RedMatic/node-red-contrib-sun-position/issues/4) und mittlerweile gefixed sein sollte.

Welche Version von node-red-contrib-sun-position/RedMatic hast du aktuell im Einsatz?

**Comment by drMaxxi** [comment]
Von Redmatic habe ich die neueste version vom Wochenende - nehme an, dass der node dann auch die aktuellste Version hat...

Sent from my mobile device.
________________________________
Von: Hypnos <notifications@github.com>
Gesendet: Monday, March 4, 2019 2:13:48 PM
An: HM-RedMatic/RedMatic
Cc: Michael Mian; Mention
Betreff: Re: [HM-RedMatic/RedMatic] Bug im time inject node oder in RaspberryMatic? (#157)


@drMaxxi<https://github.com/drMaxxi>: Ich konnte den Fehler leider nicht nachvollziehen.
Der Fehler sieht mir jedoch nach einem Problem aus, das in "node-red-contrib-sun-position | 0.2.2" vorhanden war (HM-RedMatic/node-red-contrib-sun-position#4<https://github.com/HM-RedMatic/node-red-contrib-sun-position/issues/4>) und mittlerweile gefixed sein sollte.

Welche Version von node-red-contrib-sun-position/RedMatic hast du aktuell im Einsatz?

**Comment by Hypnos3** [comment]
Die Version sieht man in der Palette:
![image](https://user-images.githubusercontent.com/12692680/53745662-be9a0d80-3e9f-11e9-8316-9e5aeba135c7.png)

(gelbe Hinterlegung von mir)
![image](https://user-images.githubusercontent.com/12692680/53745773-f5702380-3e9f-11e9-82d1-bef06a72c69e.png)

Ich hab dich mal auf Stack angeschrieben. Vielleicht kannst du mir da mal den Export der Inject Node zusenden. "eigentlich" sollte die Inject Node abwärts kompatibel zur Vorversion sein. Kann sein, das sich da aber der Fehlerteufel eingeschlichen hat.

**Comment by drMaxxi** [comment]
Danke, die Version ist 0.2.4. Ich schicke dir gleich den Export über Slack!

Von: Hypnos <notifications@github.com>
Antworten an: HM-RedMatic/RedMatic <reply@reply.github.com>
Datum: Montag, 4. März 2019 um 17:29
An: HM-RedMatic/RedMatic <RedMatic@noreply.github.com>
Cc: Michael Mian <m.mian@med-sci.eu>, Mention <mention@noreply.github.com>
Betreff: Re: [HM-RedMatic/RedMatic] Bug im time inject node oder in RaspberryMatic? (#157)


Die Version sieht man in der Palette:
[image]<https://user-images.githubusercontent.com/12692680/53745662-be9a0d80-3e9f-11e9-8316-9e5aeba135c7.png>

(gelbe Hinterlegung von mir)
[image]<https://user-images.githubusercontent.com/12692680/53745773-f5702380-3e9f-11e9-82d1-bef06a72c69e.png>

Ich hab dich mal auf Stack angeschrieben. Vielleicht kannst du mir da mal den Export der Inject Node zusenden. "eigentlich" sollte die Inject Node abwärts kompatibel zur Vorversion sein. Kann sein, das sich da aber der Fehlerteufel eingeschlichen hat.

**Comment by Hypnos3** [comment]
Danke für den Export. Der Fehler sollte mit version 0.2.5 jetzt weg sein.

**Comment by drMaxxi** [comment]
Danke. Habe den node upgedated und das "injecten" funktioniert wieder. Heute Abend werde ich dann auch wissen ob die Sonnenstandfunktionen wieder gehen.

**Comment by juppjuppsen** [comment]
@drMaxxi Könntest du den Flow hier oder im RedMatic Wiki zur Verfügung stellen? Danke vorab!

**Comment by Hypnos3** [comment]
@juppjuppsen: Es gibt  [im Wiki](https://github.com/HM-RedMatic/RedMatic/wiki/Flow-within-time#flow-mit-der-node-red-contrib-sun-position-nodes) bereits eine Erklärung, wie man ein Licht ein und ausschaltest. In dem Artikel ist weiter unten auch erklärt, wie das einfach mit der time-Inject Node geht.

Der Unterschied zwischen einem Licht und einer Jalousie/Dimmer ist nur, das die typischen STATE Datenpunkte einfacher Schaltaktoren ein true/false als payload benötigen und Dimmer oder Jalousie-aktoren einen LEVEL Datenpunkt haben, der einen Wert zwischen 0.0 (= 0% = geschlossen) und 1 (=100% = offen) benötigt.

Das lässt sich einfach im time-inject node beim Payload wählen:
![image](https://user-images.githubusercontent.com/12692680/53869333-4dba3900-3ff8-11e9-9406-e3ea2268f797.png)

für 30% beispielsweise:
![image](https://user-images.githubusercontent.com/12692680/53869381-66c2ea00-3ff8-11e9-8016-2d8953b3ca79.png)

Ich werde mal einen Wiki Artikel für eine einfache Zeitbasierte Jalousiesteuerung erstellen.

**Comment by drMaxxi** [comment]
Es funktioniert wieder alles - habe die Issue geschlossen.
