### ISSUE TITLE
Installfehler bei node-red-contrib-rfxcom

### ISSUE THREAD

**Issue by schloeglg** [HM-RedMatic/RedMatic#159]
Hallo.

Bei der Installation des node-red-contrib-rfxcom bekomme ich folgenden Fehler:

_serialport@6.2.2 install /node_modules/serialport
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.1 runtime=node arch=arm platform=linux)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/serialport
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above._

Eventuell gleiches Problem wie beim "Smartmeter"?
Für Hilfe wäre ich dankbar. 

Gerald

**Comment by Tscherno** [comment]
RFXCOM wäre für mich auch interessant.

**Comment by hobbyquaker** [comment]
Steckt in RedMatic 3.0.0 drin. Bitte gebt Bescheid ob es funktioniert.

**Comment by Tscherno** [comment]
Super danke. Ich versuche am Wochenende zu testen.

**Comment by schloeglg** [comment]
Hab gerade Version 3.0.1 installiert. RFX Lights funktioniert jetzt einwandfrei bei mir. Ich kann meine Intertechno Schalter bedienen. Ich hab noch einen Temperatur Sensor der auch mit dem RFXtrx433 funktionieren sollte. Das schau ich mir noch an. Aber sonst schaut das schon mal sehr gut aus.

Vielen Dank für deine rasche Umsetzung.   
Gerald

**Comment by schloeglg** [comment]
So und von meinem TH10 Temperatur Sensor bekomme ich auch Daten. 
Bin begeistert. 
Danke

**Comment by Tscherno** [comment]
Hast Du ausser anstecken noch etwas anderes gemacht? Ich habe es auf /dev/ttyUSB0 gestellt, das wäre auch vorhanden. Hatte aber vorher nen USB-Stick dran.
Spricht was dagegn den zweiten USB-Port bei Charly nutzbar zu machen?

**Comment by schloeglg** [comment]
Zum Charly kann ich dir leider nichts sagen. Ich verwende PIVCCU3 auf meinem Raspi. PiVCCU läuft ja in einem Container. Ich musste mit "sudo dpkg-reconfigure pivccu3" den RFXtrx der bei mir auf ttyUSB1 hängt an den Container weiterreichen.
